### ISSUE TITLE
新建集群名称问题

### ISSUE THREAD

**Issue by yingyun001** [eayun/ovirt-engine#20]
原来的集群名称是 '-' 或者 '.' 等特殊字符，然后编辑集群，将名称修改为 '_' ，会报错，错误如下：执行动作时出错：无法 编辑 集群。集群名称已经被使用。（此时集群里并没有名称为 _ 的集群）

**Comment by walteryang47** [comment]
该问题是由于集群的名称大小写不敏感，该规则由 VdsGroupOperationCommandBase.isVdsGroupUnique(String vdsGroupName) 内的方法决定。
'_' 和 '-' 对于大小写不敏感的情况下是相同的，而又在新建或更新集群的时候需要判断集群名称是唯一的，所以报错。
建议不修改此问题。
