### ISSUE TITLE
新建角色的窗口无法正常关闭。

### ISSUE THREAD

**Issue by yingyun001** [eayun/ovirt-engine#21]
点【配置】--【角色】--【新建】，该弹出框口弹出后，无法正常关闭。

**Comment by walteryang47** [comment]
问题已经解决，需要将新的 i18n 字符串提交至 [zanata](https://translate.zanata.org/zanata/iteration/view/EayunOS41/4.1/languages/zh-CN)

**Comment by walteryang47** [comment]
fixed in above commits
