### ISSUE TITLE
error 提示问题

### ISSUE THREAD

**Issue by yingyun001** [eayun/ovirt-engine#23]
1. 点击【数据中心】--- 选择任意一个资源 --- 点击子选项卡中的【QoS】--- 点击【Storage】--- 点击【New】--- 输入【QoS Name】--- 在 【Throughput】或者【IOps】中输入非法字符，例如：英文子母或者！@#￥%……等 ---  点击【确定】--- 可以新建成功。

2. 点击【数据中心】--- 选择任意一个资源 --- 点击子选项卡中的【QoS】---  点击【网络 QoS】--- 点击【New】--- 输入【QoS Name】--- 在 【转入的】或者【转出的】中输入非法字符，例如：英文子母或者!@#$%^&等 --- 点击【确定】--- 报错区域的边框变位红色，提示报错为：这个字段不能为空。

3. 点击【数据中心】--- 选择任意一个资源 --- 点击子选项卡中的【QoS】---  点击【CPU】--- 点击【New】--- 输入【QoS Name】--- 在【limit】中输入非法字符，例如：英文子母或者^%$#@等 --- 报错区域的边框变位红色，提示报错为：这个字段不能为空。

**Comment by walteryang47** [comment]
由于【Throughput】、【IOps】、【转入的】、【转出的】、【limit】输入框使用了 IntegerEntityModelTextBoxOnlyEditor，输入非数字的时候，gwtp 中的 view 层就自动清除输入的内容了，然后再在 gwtp 的 model 层做输入合法性验证的时候报了“这个字段不能为空” 的错误。

解决难度较大。
