### ISSUE TITLE
userportal 中的 客户资源 链接有误

### ISSUE THREAD

**Issue by walteryang47** [eayun/ovirt-engine#29]
#### 步骤：
1. 打开并登录用户门户入口
2. 切换到**基本视图**
3. 选择一台虚拟机，并点击右侧**控制台**下的**客户资源** 链接

#### 预期结果：
链接到 ```/eayunVirt```
#### 实际结果：
链接到了 ```/ovirt-engine/eayunVirt```

**Comment by yingyun001** [comment]
I have fixed this issue as above.

**Comment by walteryang47** [comment]
在 4.1.1 版本上测试，问题未解决
