### ISSUE TITLE
新建虚拟机池的时候，集群和 CPU profile 没有产生关联。

### ISSUE THREAD

**Issue by yingyun001** [eayun/ovirt-engine#32]
Default_qi 里面有个名字叫 b 的 CPU Profile 
![_109](https://cloud.githubusercontent.com/assets/7485231/7289744/f569011a-e9a6-11e4-9843-ac9a21335516.png)

但是在新建虚拟机池的时，如果选择了 Default_qi 这个集群，在【资源分配】这个选项卡里的【CPU Profile】选项并没有找到对应的名称为 b 的 CPU Profile。
![issue1](https://cloud.githubusercontent.com/assets/7485231/7289640/5a918afa-e9a5-11e4-9379-43e857393a9a.png)

**Comment by walteryang47** [comment]
fixed in above commit
